"""empty message

Revision ID: 435bc2185f6d
Revises: d107369afb7d
Create Date: 2025-04-03 11:43:54.617085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435bc2185f6d'
down_revision = 'd107369afb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comment_post_id_fkey', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
