"""empty message

Revision ID: a885099bea2b
Revises: bb106683d0e9
Create Date: 2025-04-03 11:08:03.483364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a885099bea2b'
down_revision = 'bb106683d0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
