"""empty message

Revision ID: bb106683d0e9
Revises: b162280c9e38
Create Date: 2025-04-03 10:57:18.644043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb106683d0e9'
down_revision = 'b162280c9e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_author_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key('comment_author_id_fkey', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
